# Generated by Django 2.2 on 2019-06-29 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20190629_1715'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['post_date']},
        ),
    ]
